[package]
name = "obs_switcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
obws = "0.10.0-beta.4"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
exitcode = "1.1.2"
